### ISSUE TITLE
Support diamond shape (UML conditional shape/node)

### ISSUE THREAD

**Issue by huytd** [tuanchauict/MonoSketch#509]
There are actually 2 types of diamonds:

- As a shape
<img width="246" alt="image" src="https://github.com/tuanchauict/MonoSketch/assets/613943/6d8aa961-30c6-41e0-bae9-3dc2621824e0">

- As a node
<img width="131" alt="image" src="https://github.com/tuanchauict/MonoSketch/assets/613943/03aa8cf2-db36-421e-81b8-d8a0d6ba69b0">

**Comment by tuanchauict** [comment]
Node is supported as an anchor head
```
▲           
│           
Y           
│           
◆───N──────▶
```

**Comment by huytd** [comment]
Seems good! Closing this issue for now. Thank you so much!
