### ISSUE TITLE
Suggestions for optimizing the efficiency of selected elements

### ISSUE THREAD

**Issue by qindapao** [tuanchauict/MonoSketch#538]
Hello, great to see this interesting text graph application, thank you for your work, I love this software.

When I was using it recently, I found that there is a place that is a bit inconvenient. That is, if I click an element, I want to move it immediately without clicking a second time. 

I know that the default behavior of your design is to click and drag to generate a selection box, and then determine the elements that need to be operated. This is fine, but most of the time the user actually just wants to manipulate an element. That is to say, if there is an element under the mouse, then directly operate the element, if there is no element under the mouse, then generate a selection box.

Can this be optimized? Efficiency will improve a lot.

Thank you.

![2023_06_20_12_34_47_267](https://github.com/tuanchauict/MonoSketch/assets/109883544/d8600d18-61d5-4a51-a02b-d0ac0571f84e)

**Comment by tuanchauict** [comment]
Thank you very much for using the app and suggestions.
Let me fix it.

Looks like the draw.io also has this interaction.

https://github.com/tuanchauict/MonoSketch/assets/955306/c0c82760-5535-4864-8a26-5c1c7893435b

For good UX: hover/mouse enter will automatically select the underlying shape. This is definitely doable.

But please wait a little bit, I'm in the middle of another big feature: line snapping

**Comment by qindapao** [comment]
@tuanchauict 

Thank you. That's good.
