### ISSUE TITLE
Unable to donate via Ko Fi

### ISSUE THREAD

**Issue by rossdanderson** [tuanchauict/MonoSketch#578]
Not an issue with MonoSketch itself (great app by the way) but I just tried to make a donation via Ko Fi but I get the error "Your account cannot currently make live charges." which after a quick search I think may be your Stripe payment details are set up incorrectly?

This is a similar issue I found https://github.com/jeffshee/hidamari/issues/60

All the best,
Ross

![image](https://github.com/tuanchauict/MonoSketch/assets/3797957/ec403d7b-07e2-4d78-bf88-676d3f74ac88)

**Comment by tuanchauict** [comment]
Thank you so much for your support. I really appreciate that!
Let me see how to fix this issue.

**Comment by tuanchauict** [comment]
Sorry for keeping this issue so long, the KoFi is working now. I just tested
<img width="665" alt="image" src="https://github.com/tuanchauict/MonoSketch/assets/955306/b72d817d-a69f-46df-b859-06747605c5e7">

It's a little bit weird to donate myself 😄 

Thank you very much for your support.
Have a nice day to you!
